from pynput.keyboard import Key, Controller
key=Controller()

def keypresses():
    key.press("Q")
    key.press("W")
    key.press("E")
    key.press("R")
    key.press("T")
    key.press("Y")
    key.press("U")
    key.press("I")
    key.press("O")
    key.press("P")
    key.press("A")
    key.press("S")
    key.press("D")
    key.press("F")
    key.press("G")
    key.press("H")
    key.press("J")
    key.press("K")
    key.press("L")
    key.press("Z")
    key.press("X")
    key.press("C")
    key.press("V")
    key.press("B")
    key.press("N")
    key.press("M")
